module Main exposing (..)

import Html exposing (..)
import Html.Attributes exposing (href, id, src)



-- tagname [attribute] [content]


main =
    div []
        [ h1 [ id "myh1" ] [ text "this is h1" ]
        , div []
            [ p []
                [ text "This page is generated by "
                , a [ href "https://elm-lang.org" ] [ text "Elm" ]
                ]
            , img
                [ src "https://aws1.discourse-cdn.com/standard17/uploads/elm_lang/original/1X/151e7d13625550d29b439bc509030b3921b3a7d6.png" ]
                []
            ]
        , h2 [] [ text "h2" ]
        , p [] [ text "this is paragraph" ]
        , ol []
            [ li [] [ text "ordered list no. 1" ]
            , li [] [ text "order list no. 2" ]
            ]
        , h3 [] [ text "h3" ]
        , ul []
            [ li [] [ text "unordered list 1st" ]
            , li [] [ text "unordered list 2nd" ]
            ]
        , button [] [ text "OK button" ]
        , br [] []
        , button [] [ text "NG button" ]
        ]
